### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by jcarlson** [terraform-providers/terraform-provider-random#68]
### Terraform Version
```
$ terraform -v
Terraform v0.12.5
+ provider.alks v1.3.0
+ provider.archive v1.2.0
+ provider.aws v2.21.1
+ provider.external v1.2.0
+ provider.null v2.1.0
+ provider.random v2.1.0
+ provider.template v2.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- random_shuffle

### Debug Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for
random_shuffle.public_subnets[0]
to include new values learned so far during apply, provider "random" produced
an invalid new value for .input: was null, but now
cty.ListVal([]cty.Value{cty.StringVal("subnet-085e91467d54b2027")}).

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Important Factoids
I am in the process of upgrading to Terraform 0.12. On first `apply` after upgrading, I receive this error. Unfortunately, I am unable to provide many more details, because running `terraform apply` a second time does not exhibit this error.

I am unsure what may be causing the issue, but since the one-time occurrence has been consistent when switching workspaces, I went ahead and reported an issue.

**Comment by apparentlymart** [comment]
Hi @jcarlson! Sorry for this odd error message.

Given what we see in the error message here, it looks like in your configuration for `input` you have a reference to some other resource that is exporting an AWS subnet id. If so, I expect that actually the bug here is in _that_ resource type, where it indicated during the initial plan that it would export `null` but then changed its mind once some other value was learned during the apply phase. Re-running makes the problem go away presumably because now that upstream resource already "knows" whatever value caused it to change its result, and so it produces a consistent plan both times on the second run.

Unfortunately due to some historical inconsistent behavior in the Terraform SDK (which is currently still based on the Terraform 0.11 protocol), provider implementations are currently exempt from certain safety checks that would normally catch this upstream at the original cause, and so this is being incorrectly reported at the point where you referenced the result rather than at the resource that generated that result.

If there is indeed a reference to some other resource in there, then I think this will need to be opened against whatever provider implements that resource type instead; given that it's an AWS subnet id, I'd guess it's some resource type from the AWS provider.

**Comment by jcarlson** [comment]
Martin,

You are spot on. Basically, I have a module that enumerates all the subnets
in an AWS VPC and picks two at random. This is used in conjunction with an
ElasticSearch cluster, which requires two subnets for multi-AZ deployments.

I'll keep an eye on this, and if it continually crops up after I complete
my migration to Terraform 0.12, I will file a ticket with the AWS provider
repository.

Thanks!

~ jarrod

**Comment by apparentlymart** [comment]
Great, thanks for following up @jcarlson!

Given that, there isn't any fix we could make here in the `random` provider to avoid that message, so I'm going to close this now and hopefully if it arises again we can capture it in the AWS provider repository instead.

Design work for updating the SDK to be based on the Terraform 0.12 protocol is getting started now, so hopefully before too long the AWS provider will no longer be treated to this special legacy protocol exception and Terraform Core will be able to report the problem at its source, which will cause the error message for this case to contain a more specific description of the problem.

Thanks for reporting this, and sorry that the error message is currently misleading about where exactly the problem arose.

**Comment by jcarlson** [comment]
@apparentlymart I ran into this issue again and decided to commit some brain cycles to finding a workaround. Mostly by accident, I noticed that I am able to reliably reproduce this issue with `random` provider version `2.1.0`, but if I upgrade that to `2.1.1` or greater, I am not able to reproduce it; all other providers were held constant as listed in this issue.

This leads me to believe that it is (or was) a bug in the `random` provider after all, but given I cannot reproduce it in newer versions of the provider, I'm not sure any further time is warranted here.

Thanks for your help.
